users:
    resource: AppBundle\Controller\DefaultController
    type:     rest

products:
    resource: ProductBundle\Controller\ProductController
    type:     rest

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"